server:
  port: 8080

spring:
  application:
    name: onboarding

  datasource:
    url: jdbc:mariadb://localhost:3306/onboarding_db
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret: onboardingsecretkey12345678901234567890123  # Secret key for JWT encoding
    expirationMs: 86400000  # Token expiration in milliseconds (1 day)

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
